version: '3'

services:
  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    ports:
      - 8080:4000
    networks:
      - app
  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    ports:
      - 9090:80
      - 9091:443
    networks:
      - app
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    networks:
      - app

networks:
  app:
    name: app

